---
ID: "281d054d-59fa-4b51-8bab-815b09e0014b"
Parent: "56161ee3-93b5-465f-bff7-ea4464145edd"
Template: "56161ee3-93b5-465f-bff7-ea4464145edd"
Path: /sitecore/templates/Project/Skate Park/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {56161EE3-93B5-465F-BFF7-EA4464145EDD}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230824T153032Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\amit.iu.kumar@accenture.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\amit.iu.kumar@accenture.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eaadb7b1-cb13-4882-a1c7-83b97063c332"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\amit.iu.kumar@accenture.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230824T153035Z
    - ID: "de2fb775-2078-49e8-a54d-ecec639caba8"
      Hint: Title
      Value: $name
