---
ID: "05acf4c7-0ede-4069-a55c-1621c8a07bc6"
Parent: "d6511834-5f1c-470d-acc4-78f05dd5196e"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/TAC/Events/Presentation/Headless Variants/EventContent/Default
BranchID: "37fcd64e-ccf5-44d2-a348-8b8afacaa8cb"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E103376C-1205-41E9-9195-4C8E4E5A3DD1}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230825T184713Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\amit.iu.kumar@accenture.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\amit.iu.kumar@accenture.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ca861b69-eba2-436a-b42b-962832b5849c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\amit.iu.kumar@accenture.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230825T184713Z
