---
ID: "3c766ffd-3544-4fcb-a85c-b45c1ea4e634"
Parent: "251b5bf5-0f5e-43e4-a1b8-9389ddb3e41f"
Template: "251b5bf5-0f5e-43e4-a1b8-9389ddb3e41f"
Path: "/sitecore/templates/Project/Skate Park/Skate-Park-Templates/Helmets/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230824T163330Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "23f4be29-50f4-4c0c-9483-bce63cc6a1b8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\amit.iu.kumar@accenture.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230824T163330Z
